goodbyeTimeoutMs: 2500
iptablesPath: script/iptables-ban.sh
serverPort: 8545

server:
  type: simple
  applicationContextPath: /
  connector:
    type: http
    port: 8545

logging:
  level: INFO
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
